-- Public exercises seed
-- Run in Supabase SQL editor
-- Clears and reseeds public_exercises with standardized naming

DELETE FROM public_exercises;

INSERT INTO public_exercises (name, exercise_type_id, primary_muscle, other_muscles)
SELECT v.name, et.id, v.primary_muscle, v.other_muscles
FROM (VALUES

  -- ── CHEST ────────────────────────────────────────────────────────────────
  ('Bench Press (Barbell)',                    'weight_reps',      'Chest', ARRAY['Triceps','Shoulders']),
  ('Bench Press (Dumbbell)',                   'weight_reps',      'Chest', ARRAY['Triceps','Shoulders']),
  ('Bench Press (Smith Machine)',              'weight_reps',      'Chest', ARRAY['Triceps','Shoulders']),
  ('Incline Bench Press (Barbell)',            'weight_reps',      'Chest', ARRAY['Shoulders','Triceps']),
  ('Incline Bench Press (Dumbbell)',           'weight_reps',      'Chest', ARRAY['Shoulders','Triceps']),
  ('Incline Bench Press (Smith Machine)',      'weight_reps',      'Chest', ARRAY['Shoulders','Triceps']),
  ('Decline Bench Press (Barbell)',            'weight_reps',      'Chest', ARRAY['Triceps']),
  ('Chest Press (Machine)',                    'weight_reps',      'Chest', ARRAY['Triceps','Shoulders']),
  ('Chest Press (Plate-Loaded)',               'weight_reps',      'Chest', ARRAY['Triceps','Shoulders']),
  ('Incline Chest Press (Machine)',            'weight_reps',      'Chest', ARRAY['Shoulders','Triceps']),
  ('Incline Chest Press (Plate-Loaded)',       'weight_reps',      'Chest', ARRAY['Shoulders','Triceps']),
  ('Decline Chest Press (Machine)',            'weight_reps',      'Chest', ARRAY['Triceps']),
  ('Decline Chest Press (Plate-Loaded)',       'weight_reps',      'Chest', ARRAY['Triceps']),
  ('Decline Chest Press (Smith Machine)',      'weight_reps',      'Chest', ARRAY['Triceps']),
  ('Reverse-Grip Bench Press (Barbell)',       'weight_reps',      'Chest', ARRAY['Triceps']),
  ('Chest Fly (Dumbbell)',                     'weight_reps',      'Chest', NULL),
  ('Incline Chest Fly (Dumbbell)',             'weight_reps',      'Chest', NULL),
  ('Chest Fly (Cable)',                        'weight_reps',      'Chest', NULL),
  ('Cable Crossover (Cable)',                  'weight_reps',      'Chest', NULL),
  ('Pec Deck Fly (Machine)',                   'weight_reps',      'Chest', NULL),
  ('Push-Up (Bodyweight)',                     'bodyweight_reps',  'Chest', ARRAY['Triceps','Shoulders']),

  -- ── BACK ─────────────────────────────────────────────────────────────────
  ('Bent-Over Row (Barbell)',                  'weight_reps', 'Back', ARRAY['Biceps']),
  ('Bent-Over Row (Dumbbell)',                 'weight_reps', 'Back', ARRAY['Biceps']),
  ('Bent-Over Row (Smith Machine)',            'weight_reps', 'Back', ARRAY['Biceps']),
  ('Pull-Up (Bodyweight)',                     'bodyweight_reps',    'Back', ARRAY['Biceps']),
  ('Pull-Up (Weighted)',                       'weighted_bodyweight', 'Back', ARRAY['Biceps']),
  ('Pull-Up (Assisted)',                       'assisted_bodyweight', 'Back', ARRAY['Biceps']),
  ('Chin-Up (Bodyweight)',                     'bodyweight_reps',    'Back', ARRAY['Biceps']),
  ('Chin-Up (Weighted)',                       'weighted_bodyweight', 'Back', ARRAY['Biceps']),
  ('Chin-Up (Assisted)',                       'assisted_bodyweight', 'Back', ARRAY['Biceps']),
  ('Lat Pulldown (Machine)',                   'weight_reps', 'Back', ARRAY['Biceps']),
  ('Lat Pulldown (Cable)',                     'weight_reps', 'Back', ARRAY['Biceps']),
  ('Lat Pulldown (Plate-Loaded)',              'weight_reps', 'Back', ARRAY['Biceps']),
  ('Seated Row (Cable)',                       'weight_reps', 'Back', ARRAY['Biceps']),
  ('Seated Row (Machine)',                     'weight_reps', 'Back', ARRAY['Biceps']),
  ('Seated Row (Plate-Loaded)',                'weight_reps', 'Back', ARRAY['Biceps']),
  ('High Row (Machine)',                       'weight_reps', 'Back', ARRAY['Biceps']),
  ('High Row (Plate-Loaded)',                  'weight_reps', 'Back', ARRAY['Biceps']),
  ('Low Row (Machine)',                        'weight_reps', 'Back', ARRAY['Biceps']),
  ('Low Row (Plate-Loaded)',                   'weight_reps', 'Back', ARRAY['Biceps']),
  ('Chest-Supported Row (Machine)',            'weight_reps', 'Back', ARRAY['Biceps']),
  ('Chest-Supported Row (Plate-Loaded)',       'weight_reps', 'Back', ARRAY['Biceps']),
  ('T-Bar Row (Machine)',                      'weight_reps', 'Back', ARRAY['Biceps']),
  ('T-Bar Row (Plate-Loaded)',                 'weight_reps', 'Back', ARRAY['Biceps']),
  ('Seal Row (Barbell)',                       'weight_reps', 'Back', ARRAY['Biceps']),
  ('Landmine Row (Barbell)',                   'weight_reps', 'Back', ARRAY['Biceps']),
  ('Meadows Row (Barbell)',                    'weight_reps', 'Back', ARRAY['Biceps']),
  ('Pendlay Row (Barbell)',                    'weight_reps', 'Back', ARRAY['Biceps']),
  ('Reverse-Grip Row (Barbell)',               'weight_reps', 'Back', ARRAY['Biceps']),
  ('Pullover (Dumbbell)',                      'weight_reps', 'Back', ARRAY['Chest']),
  ('Back Extension (Bodyweight)',              'bodyweight_reps',    'Back', NULL),
  ('Back Extension (Weighted)',                'weighted_bodyweight', 'Back', NULL),
  ('Back Extension (Machine)',                 'weight_reps',        'Back', NULL),

  -- ── SHOULDERS ────────────────────────────────────────────────────────────
  ('Overhead Press (Barbell)',                 'weight_reps', 'Shoulders', ARRAY['Triceps']),
  ('Overhead Press (Dumbbell)',                'weight_reps', 'Shoulders', ARRAY['Triceps']),
  ('Overhead Press (Machine)',                 'weight_reps', 'Shoulders', ARRAY['Triceps']),
  ('Overhead Press (Plate-Loaded)',            'weight_reps', 'Shoulders', ARRAY['Triceps']),
  ('Arnold Press (Dumbbell)',                  'weight_reps', 'Shoulders', ARRAY['Triceps']),
  ('Lateral Raise (Dumbbell)',                 'weight_reps', 'Shoulders', NULL),
  ('Lateral Raise (Cable)',                    'weight_reps', 'Shoulders', NULL),
  ('Lateral Raise (Machine)',                  'weight_reps', 'Shoulders', NULL),
  ('Front Raise (Dumbbell)',                   'weight_reps', 'Shoulders', NULL),
  ('Rear Delt Fly (Dumbbell)',                 'weight_reps', 'Shoulders', ARRAY['Traps','Back']),
  ('Rear Delt Fly (Machine)',                  'weight_reps', 'Shoulders', ARRAY['Traps','Back']),
  ('Rear Delt Fly (Cable)',                    'weight_reps', 'Shoulders', ARRAY['Traps','Back']),
  ('Face Pull (Cable)',                        'weight_reps', 'Shoulders', ARRAY['Traps','Back']),
  ('Upright Row (Barbell)',                    'weight_reps', 'Shoulders', ARRAY['Traps']),
  ('Upright Row (Dumbbell)',                   'weight_reps', 'Shoulders', ARRAY['Traps']),

  -- ── BICEPS ───────────────────────────────────────────────────────────────
  ('Bicep Curl (Barbell)',                     'weight_reps', 'Biceps', NULL),
  ('Bicep Curl (Dumbbell)',                    'weight_reps', 'Biceps', NULL),
  ('Bicep Curl (Machine)',                     'weight_reps', 'Biceps', NULL),
  ('Bicep Curl (Cable)',                       'weight_reps', 'Biceps', NULL),
  ('Bicep Curl (Plate-Loaded)',                'weight_reps', 'Biceps', NULL),
  ('Hammer Curl (Dumbbell)',                   'weight_reps', 'Biceps', ARRAY['Forearms']),
  ('Hammer Curl (Cable)',                      'weight_reps', 'Biceps', ARRAY['Forearms']),
  ('Concentration Curl (Dumbbell)',            'weight_reps', 'Biceps', NULL),
  ('Incline Curl (Dumbbell)',                  'weight_reps', 'Biceps', NULL),
  ('Preacher Curl (Barbell)',                  'weight_reps', 'Biceps', NULL),
  ('Preacher Curl (Dumbbell)',                 'weight_reps', 'Biceps', NULL),
  ('Preacher Curl (Cable)',                    'weight_reps', 'Biceps', NULL),
  ('Preacher Curl (Machine)',                  'weight_reps', 'Biceps', NULL),
  ('Drag Curl (Barbell)',                      'weight_reps', 'Biceps', NULL),
  ('Reverse Curl (Barbell)',                   'weight_reps', 'Biceps', ARRAY['Forearms']),
  ('Zottman Curl (Dumbbell)',                  'weight_reps', 'Biceps', ARRAY['Forearms']),

  -- ── TRICEPS ──────────────────────────────────────────────────────────────
  ('Close-Grip Bench Press (Barbell)',         'weight_reps',      'Triceps', ARRAY['Chest']),
  ('Close-Grip Bench Press (Smith Machine)',   'weight_reps',      'Triceps', ARRAY['Chest']),
  ('Dip (Bodyweight)',                         'bodyweight_reps',    'Triceps', ARRAY['Chest','Shoulders']),
  ('Dip (Weighted)',                           'weighted_bodyweight', 'Triceps', ARRAY['Chest','Shoulders']),
  ('Dip (Assisted)',                           'assisted_bodyweight', 'Triceps', ARRAY['Chest','Shoulders']),
  ('Diamond Push-Up (Bodyweight)',             'bodyweight_reps',  'Triceps', ARRAY['Chest']),
  ('Close-Grip Push-Up (Bodyweight)',          'bodyweight_reps',  'Triceps', ARRAY['Chest']),
  ('JM Press (Barbell)',                       'weight_reps',      'Triceps', ARRAY['Chest']),
  ('JM Press (Machine)',                       'weight_reps',      'Triceps', ARRAY['Chest']),
  ('JM Press (Smith Machine)',                 'weight_reps',      'Triceps', ARRAY['Chest']),
  ('JM Press (Plate-Loaded)',                  'weight_reps',      'Triceps', ARRAY['Chest']),
  ('Skullcrusher (Barbell)',                   'weight_reps',      'Triceps', NULL),
  ('Skullcrusher (Dumbbell)',                  'weight_reps',      'Triceps', NULL),
  ('Triceps Extension (Machine)',              'weight_reps',      'Triceps', NULL),
  ('Triceps Extension (Cable)',                'weight_reps',      'Triceps', NULL),
  ('Triceps Pushdown (Cable)',                 'weight_reps',      'Triceps', NULL),
  ('Overhead Triceps Extension (Dumbbell)',    'weight_reps',      'Triceps', NULL),
  ('Overhead Triceps Extension (Cable)',       'weight_reps',      'Triceps', NULL),
  ('Overhead Triceps Extension (Barbell)',     'weight_reps',      'Triceps', NULL),
  ('Kickback (Dumbbell)',                      'weight_reps',      'Triceps', NULL),
  ('Kickback (Cable)',                         'weight_reps',      'Triceps', NULL),

  -- ── TRAPS ────────────────────────────────────────────────────────────────
  ('Shrug (Barbell)',                          'weight_reps', 'Traps', NULL),
  ('Shrug (Dumbbell)',                         'weight_reps', 'Traps', NULL),
  ('Shrug (Smith Machine)',                    'weight_reps', 'Traps', NULL),
  ('Shrug (Kettlebell)',                       'weight_reps', 'Traps', NULL),
  ('Power Shrug (Barbell)',                    'weight_reps', 'Traps', ARRAY['Back']),
  ('Rack Pull (Barbell)',                      'weight_reps', 'Traps', ARRAY['Back']),
  ('Rack Pull (Smith Machine)',                'weight_reps', 'Traps', ARRAY['Back']),

  -- ── FOREARMS ─────────────────────────────────────────────────────────────
  ('Wrist Curl (Barbell)',                     'weight_reps', 'Forearms', NULL),
  ('Wrist Curl (Dumbbell)',                    'weight_reps', 'Forearms', NULL),
  ('Wrist Curl (Cable)',                       'weight_reps', 'Forearms', NULL),
  ('Wrist Curl (Machine)',                     'weight_reps', 'Forearms', NULL),
  ('Reverse Wrist Curl (Barbell)',             'weight_reps', 'Forearms', NULL),
  ('Reverse Wrist Curl (Dumbbell)',            'weight_reps', 'Forearms', NULL),
  ('Reverse Wrist Curl (Cable)',               'weight_reps', 'Forearms', NULL),
  ('Reverse Wrist Curl (Machine)',             'weight_reps', 'Forearms', NULL),

  -- ── CORE ─────────────────────────────────────────────────────────────────
  ('Farmer''s Carry (Dumbbell)',               'weight_reps', 'Core', ARRAY['Forearms']),
  ('Farmer''s Carry (Kettlebell)',             'weight_reps', 'Core', ARRAY['Forearms']),
  ('Suitcase Carry (Dumbbell)',                'weight_reps', 'Core', ARRAY['Forearms']),
  ('Suitcase Carry (Kettlebell)',              'weight_reps', 'Core', ARRAY['Forearms']),
  ('Crunch (Bodyweight)',                      'bodyweight_reps',    'Core', NULL),
  ('Crunch (Weighted)',                        'weighted_bodyweight', 'Core', NULL),
  ('Crunch (Cable)',                           'weight_reps',        'Core', NULL),
  ('Crunch (Machine)',                         'weight_reps',        'Core', NULL),
  ('Sit-Up (Bodyweight)',                      'bodyweight_reps',    'Core', NULL),
  ('Sit-Up (Weighted)',                        'weighted_bodyweight', 'Core', NULL),
  ('Incline Sit-Up (Bodyweight)',              'bodyweight_reps',    'Core', NULL),
  ('Incline Sit-Up (Weighted)',                'weighted_bodyweight', 'Core', NULL),
  ('Russian Twist (Bodyweight)',               'bodyweight_reps',    'Core', NULL),
  ('Russian Twist (Weighted)',                 'weighted_bodyweight', 'Core', NULL),
  ('Ab Wheel Rollout (Bodyweight)',            'bodyweight_reps',  'Core', ARRAY['Shoulders']),
  ('Hanging Leg Raise (Bodyweight)',           'bodyweight_reps',    'Core', NULL),
  ('Hanging Leg Raise (Weighted)',             'weighted_bodyweight', 'Core', NULL),
  ('Hanging Knee Raise (Bodyweight)',          'bodyweight_reps',    'Core', NULL),
  ('Hanging Knee Raise (Weighted)',            'weighted_bodyweight', 'Core', NULL),

  -- ── GLUTES ───────────────────────────────────────────────────────────────
  ('Deadlift (Barbell)',                       'weight_reps', 'Glutes', ARRAY['Hamstrings','Back']),
  ('Deadlift (Dumbbell)',                      'weight_reps', 'Glutes', ARRAY['Hamstrings','Back']),
  ('Hip Thrust (Barbell)',                     'weight_reps',     'Glutes', ARRAY['Hamstrings']),
  ('Hip Thrust (Machine)',                     'weight_reps',     'Glutes', ARRAY['Hamstrings']),
  ('Glute Bridge (Barbell)',                   'weight_reps',     'Glutes', ARRAY['Hamstrings']),
  ('Glute Bridge (Dumbbell)',                  'weight_reps',     'Glutes', ARRAY['Hamstrings']),
  ('Glute Bridge (Bodyweight)',                'bodyweight_reps', 'Glutes', ARRAY['Hamstrings']),
  ('Pull-Through (Cable)',                     'weight_reps',     'Glutes', ARRAY['Hamstrings']),
  ('Kettlebell Swing (Kettlebell)',            'weight_reps',     'Glutes', ARRAY['Hamstrings','Back']),
  ('Reverse Lunge (Barbell)',                  'weight_reps',     'Glutes', ARRAY['Quads']),
  ('Reverse Lunge (Dumbbell)',                 'weight_reps',     'Glutes', ARRAY['Quads']),
  ('Reverse Lunge (Kettlebell)',               'weight_reps',     'Glutes', ARRAY['Quads']),
  ('Reverse Lunge (Smith Machine)',            'weight_reps',     'Glutes', ARRAY['Quads']),

  -- ── QUADS ────────────────────────────────────────────────────────────────
  ('Back Squat (Barbell)',                     'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Back Squat (Smith Machine)',               'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Front Squat (Barbell)',                    'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Front Squat (Smith Machine)',              'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Overhead Squat (Barbell)',                 'weight_reps', 'Quads', ARRAY['Shoulders']),
  ('Hack Squat (Machine)',                     'weight_reps', 'Quads', ARRAY['Glutes','Hamstrings']),
  ('Hack Squat (Plate-Loaded)',                'weight_reps', 'Quads', ARRAY['Glutes','Hamstrings']),
  ('Leg Press (Machine)',                      'weight_reps', 'Quads', ARRAY['Glutes','Hamstrings']),
  ('Leg Press (Plate-Loaded)',                 'weight_reps', 'Quads', ARRAY['Glutes','Hamstrings']),
  ('Leg Extension (Machine)',                  'weight_reps', 'Quads', NULL),
  ('Leg Extension (Plate-Loaded)',             'weight_reps', 'Quads', NULL),
  ('Bulgarian Split Squat (Barbell)',          'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Bulgarian Split Squat (Dumbbell)',         'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Bulgarian Split Squat (Kettlebell)',       'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Split Squat (Barbell)',                    'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Split Squat (Dumbbell)',                   'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Goblet Squat (Dumbbell)',                  'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Goblet Squat (Kettlebell)',                'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Lunge (Barbell)',                          'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Lunge (Dumbbell)',                         'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Lunge (Smith Machine)',                    'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Walking Lunge (Dumbbell)',                 'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Walking Lunge (Kettlebell)',               'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Step-Up (Barbell)',                        'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Step-Up (Dumbbell)',                       'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Step-Up (Kettlebell)',                     'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Step-Up (Smith Machine)',                  'weight_reps', 'Quads', ARRAY['Glutes']),
  ('Sissy Squat (Bodyweight)',                 'bodyweight_reps',    'Quads', NULL),
  ('Sissy Squat (Weighted)',                   'weighted_bodyweight', 'Quads', NULL),

  -- ── HAMSTRINGS ───────────────────────────────────────────────────────────
  ('Romanian Deadlift (Barbell)',              'weight_reps', 'Hamstrings', ARRAY['Glutes','Back']),
  ('Romanian Deadlift (Dumbbell)',             'weight_reps', 'Hamstrings', ARRAY['Glutes','Back']),
  ('Romanian Deadlift (Plate-Loaded)',         'weight_reps', 'Hamstrings', ARRAY['Glutes','Back']),
  ('Romanian Deadlift (Kettlebell)',           'weight_reps', 'Hamstrings', ARRAY['Glutes','Back']),
  ('Single-Leg Romanian Deadlift (Barbell)',   'weight_reps', 'Hamstrings', ARRAY['Glutes']),
  ('Single-Leg Romanian Deadlift (Dumbbell)',  'weight_reps', 'Hamstrings', ARRAY['Glutes']),
  ('Single-Leg Romanian Deadlift (Kettlebell)','weight_reps', 'Hamstrings', ARRAY['Glutes']),
  ('Stiff-Leg Deadlift (Barbell)',             'weight_reps', 'Hamstrings', ARRAY['Glutes','Back']),
  ('Stiff-Leg Deadlift (Dumbbell)',            'weight_reps', 'Hamstrings', ARRAY['Glutes','Back']),
  ('Stiff-Leg Deadlift (Smith Machine)',       'weight_reps', 'Hamstrings', ARRAY['Glutes','Back']),
  ('Good Morning (Barbell)',                   'weight_reps', 'Hamstrings', ARRAY['Back','Glutes']),
  ('Good Morning (Plate-Loaded)',              'weight_reps', 'Hamstrings', ARRAY['Back','Glutes']),
  ('Good Morning (Smith Machine)',             'weight_reps', 'Hamstrings', ARRAY['Back','Glutes']),
  ('Lying Leg Curl (Machine)',                 'weight_reps', 'Hamstrings', NULL),
  ('Seated Leg Curl (Machine)',                'weight_reps', 'Hamstrings', NULL),
  ('Glute-Ham Raise (Machine)',                'weight_reps', 'Hamstrings', ARRAY['Glutes']),
  ('Nordic Curl (Bodyweight)',                 'bodyweight_reps',    'Hamstrings', ARRAY['Glutes']),
  ('Nordic Curl (Assisted)',                   'assisted_bodyweight', 'Hamstrings', ARRAY['Glutes']),
  ('Nordic Curl (Weighted)',                   'weighted_bodyweight', 'Hamstrings', ARRAY['Glutes']),

  -- ── CALVES ───────────────────────────────────────────────────────────────
  ('Standing Calf Raise (Machine)',            'weight_reps',     'Calves', NULL),
  ('Seated Calf Raise (Machine)',              'weight_reps',     'Calves', NULL),
  ('Donkey Calf Raise (Machine)',              'weight_reps',     'Calves', NULL),
  ('Calf Raise (Dumbbell)',                    'weight_reps',     'Calves', NULL),
  ('Calf Raise (Bodyweight)',                  'bodyweight_reps', 'Calves', NULL)

) AS v(name, type_key, primary_muscle, other_muscles)
JOIN exercise_types et ON et.key = v.type_key;
